apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awesome-application-ingress
  namespace: __NAMESPACE__
spec:
  ingressClassName: traefik
  rules:
  - host: ['*']
    http:
      paths:
      - backend:
          service:
            name: app1-service
            port:
              name: app1-service-http-port
        path: /__NAMESPACE__
        pathType: Prefix