---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awesome-application-ingress
  namespace: __NAMESPACE__
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: argocd.example.tld
    http:
      paths:
      - backend:
          service:
            name: app1-service
            port:
              name: http-port
        path: /__NAMESPACE__
        pathType: Prefix