apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-issue-11-118
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: awesome-application
    expires: 1684993982
    suspend-start: 1684984882
    suspend-end: 1684985782
    maximum-uptime: 10000
spec:
  project: default
  source:
    repoURL: http://gitlab:8080/lab/deployment-maintenance.git
    path: deployments/lab/helm-manifests/app-issue-11-118
    helm:
      passCredentials: false
      valueFiles:
      - values.yaml
      ignoreMissingValueFiles: false
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-issue-11-118
  info:
  - name: 'ApplicationName'
    value: 'Awesome Application'
  - name: 'Branch'
    value: 'issue-11'
  - name: 'JenkinsBuildNr'
    value: '118'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - Replace=true
    managedNamespaceMetadata:
      labels:
        any: label
        you: like
      annotations:
        the: same
        applies: for
        annotations: on-the-namespace
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager
  revisionHistoryLimit: 10
