apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __NAMESPACE__
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: awesome-application
    expires: __EXPIRES__
    suspend-start: __SUSPEND_STARTS__
    suspend-end: __SUSPENDS_ENDS__
    maximum-uptime: __MAX_UPTIME__
spec:
  project: default
  source:
    repoURL: __MAINTENANCE_REPO__
    path: __TARGET_HELM_DEPLOYMENT_DIRECTORY__
    helm:
      passCredentials: false
      valueFiles:
      - values.yaml
      ignoreMissingValueFiles: false
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: __NAMESPACE__
  info:
  - name: 'ApplicationName'
    value: 'Awesome Application'
  - name: 'Branch'
    value: '__BRANCH__'
  - name: 'JenkinsBuildNr'
    value: '__JENKINS_BUILD_NR__'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - Replace=true
    managedNamespaceMetadata:
      labels:
        any: label
        you: like
      annotations:
        the: same
        applies: for
        annotations: on-the-namespace
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager
  revisionHistoryLimit: 10
